function data = importfile_csv(filename, dataLines)
%IMPORTFILE Import data from a text file
%  GOMENTUMF5RUN1EGOFROMSTART = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  GOMENTUMF5RUN1EGOFROMSTART = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  GoMentumF5Run1egofromstart = importfile("/home/yash/Documents/MATLAB/AAA_Data_Jan/ScenarioF5_Run1-20200213T193920Z-001/ScenarioF5_Run1/GoMentum_run/GoMentum_F5_Run1_ego_from_start.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Feb-2020 12:09:13

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "timestamp_sec", "position_x", "position_y", "heading"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data = readtable(filename, opts);

end